name: Hide Profiles

on: workflow_dispatch

jobs: 
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.3.4
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libcairo2-dev pkg-config python3-dev
        pkg-config --modversion cairo
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Hide profiles
      run: python hide_profiles.py ${{ secrets.GITHUB_TOKEN }} ${{ secrets.JOBBOARD_TOKEN }}
